import api from './axios'
export const getDashboard  = ()     => api.get('/admin/dashboard')
export const getAllListings = (params)=>api.get('/admin/listings', { params })
export const approveListing= (id)   => api.patch(`/admin/listings/${id}/approve`)
export const rejectListing = (id, data) => api.patch(`/admin/listings/${id}/reject`, data)
export const approveEdit   = (id)   => api.patch(`/admin/listings/${id}/approve-edit`)
export const rejectEdit    = (id, data) => api.patch(`/admin/listings/${id}/reject-edit`, data)
export const featureListing= (id)   => api.patch(`/admin/listings/${id}/feature`)
export const getAllProjects = (params)=>api.get('/admin/projects', { params })
export const approveProject= (id)   => api.patch(`/admin/projects/${id}/approve`)
export const rejectProject = (id, data) => api.patch(`/admin/projects/${id}/reject`, data)
export const getAllEnquiries= (params)=>api.get('/admin/enquiries', { params })
export const updateEnquiry = (id, data) => api.patch(`/admin/enquiries/${id}`, data)
export const logCall       = (id, data) => api.post(`/admin/enquiries/${id}/log-call`, data)
export const getAllDeals   = (params)=>api.get('/admin/deals', { params })
export const createDeal   = (data)  => api.post('/admin/deals', data)
export const updateDeal   = (id, data)=>api.patch(`/admin/deals/${id}`, data)
export const getAllUsers   = (params)=>api.get('/admin/users', { params })
export const updateUser   = (id, data)=>api.patch(`/admin/users/${id}`, data)
